# Absolute Maximum Scaling

In [2]:
import pandas as pd
df = pd.read_csv('wine_data.csv')
print(df.head())

   1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29  5.64  1.04  3.92  \
0  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40
1  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17
2  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45
3  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93
4  1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75  1.05  2.85

   1065
0  1050
1  1185
2  1480
3   735
4  1450

Now letâ€™s  evaluate the absolute maximum values of the columns.

In [3]:
import numpy as np
max_vals = np.max(np.abs(df))
max_vals

np.float64(1680.0)

Now we are supposed to subtract these values from the data and then divide the results from the maximum values as well.

In [4]:
print((df - max_vals) / max_vals)

            1     14.23      1.71      2.43      15.6       127       2.8  \
0   -0.999405 -0.992143 -0.998940 -0.998726 -0.993333 -0.940476 -0.998423
1   -0.999405 -0.992167 -0.998595 -0.998411 -0.988929 -0.939881 -0.998333
2   -0.999405 -0.991446 -0.998839 -0.998512 -0.990000 -0.932738 -0.997708
3   -0.999405 -0.992119 -0.998458 -0.998292 -0.987500 -0.929762 -0.998333
4   -0.999405 -0.991548 -0.998952 -0.998542 -0.990952 -0.933333 -0.998054
..        ...       ...       ...       ...       ...       ...       ...
172 -0.998214 -0.991839 -0.996637 -0.998542 -0.987798 -0.943452 -0.999000
173 -0.998214 -0.992024 -0.997673 -0.998524 -0.986310 -0.939286 -0.998929
174 -0.998214 -0.992101 -0.997452 -0.998655 -0.988095 -0.928571 -0.999054
175 -0.998214 -0.992161 -0.998458 -0.998589 -0.988095 -0.928571 -0.999018
176 -0.998214 -0.991589 -0.997560 -0.998369 -0.985417 -0.942857 -0.998780

         3.06       .28      2.29      5.64      1.04      3.92      1065
0   -0.998357 -0.999845 -0.999238 -0.997393 -0.999375 -0.997976 -0.375000
1   -0.998071 -0.999821 -0.998327 -0.996619 -0.999387 -0.998113 -0.294643
2   -0.997923 -0.999857 -0.998702 -0.995357 -0.999488 -0.997946 -0.119048
3   -0.998399 -0.999768 -0.998917 -0.997429 -0.999381 -0.998256 -0.562500
4   -0.997982 -0.999798 -0.998827 -0.995982 -0.999375 -0.998304 -0.136905
..        ...       ...       ...       ...       ...       ...       ...
172 -0.999637 -0.999690 -0.999369 -0.995417 -0.999619 -0.998964 -0.559524
173 -0.999554 -0.999744 -0.999161 -0.995655 -0.999583 -0.999071 -0.553571
174 -0.999589 -0.999744 -0.999196 -0.993929 -0.999649 -0.999071 -0.502976
175 -0.999595 -0.999685 -0.999131 -0.994464 -0.999643 -0.999036 -0.500000
176 -0.999548 -0.999667 -0.999196 -0.994524 -0.999637 -0.999048 -0.666667

[177 rows x 14 columns]

# Min-Max Scaling

In [5]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, 
						columns=df.columns)
scaled_df.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,0.0,0.571053,0.205534,0.417112,0.030928,0.326087,0.575862,0.510549,0.245283,0.274448,0.264505,0.463415,0.780220,0.550642
1,0.0,0.560526,0.320158,0.700535,0.412371,0.336957,0.627586,0.611814,0.320755,0.757098,0.375427,0.447154,0.695971,0.646933
2,0.0,0.878947,0.239130,0.609626,0.319588,0.467391,0.989655,0.664557,0.207547,0.558360,0.556314,0.308943,0.798535,0.857347
3,0.0,0.581579,0.365613,0.807487,0.536082,0.521739,0.627586,0.495781,0.490566,0.444795,0.259386,0.455285,0.608059,0.325963
4,0.0,0.834211,0.201581,0.582888,0.237113,0.456522,0.789655,0.643460,0.396226,0.492114,0.466724,0.463415,0.578755,0.835949

# Normalization

In [5]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data,
						columns=df.columns)
print(scaled_df.head())

          1     14.23      1.71      2.43      15.6       127       2.8  \
0  0.000948  0.012513  0.001687  0.002029  0.010617  0.094794  0.002512
1  0.000841  0.011063  0.001984  0.002245  0.015636  0.084906  0.002354
2  0.000674  0.009680  0.001314  0.001684  0.011317  0.076119  0.002593
3  0.001343  0.017775  0.003477  0.003853  0.028193  0.158417  0.003759
4  0.000688  0.009763  0.001210  0.001684  0.010450  0.077002  0.002248

       3.06       .28      2.29      5.64      1.04      3.92      1065
0  0.002616  0.000246  0.001213  0.004152  0.000995  0.003223  0.995336
1  0.002724  0.000252  0.002362  0.004775  0.000866  0.002665  0.996175
2  0.002351  0.000162  0.001468  0.005254  0.000579  0.002324  0.996961
3  0.003611  0.000524  0.002443  0.005800  0.001396  0.003934  0.986752
4  0.002331  0.000234  0.001354  0.004641  0.000722  0.001959  0.996907

# Standardization

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data,
						columns=df.columns)
print(scaled_df.head())

          1     14.23      1.71      2.43      15.6       127       2.8  \
0 -1.222468  0.255824 -0.501624 -0.824485 -2.500110  0.029180  0.572666
1 -1.222468  0.206229  0.018020  1.107690 -0.275639  0.099932  0.812784
2 -1.222468  1.706501 -0.349315  0.487935 -0.816726  0.948953  2.493609
3 -1.222468  0.305420  0.224086  1.836812  0.445811  1.302712  0.812784
4 -1.222468  1.495719 -0.519543  0.305655 -1.297693  0.878201  1.565153

       3.06       .28      2.29      5.64      1.04      3.92      1065
0  0.739636 -0.823139 -0.538575 -0.291130  0.407100  1.131698  0.971052
1  1.221645 -0.501337  2.145975  0.269729  0.319567  0.804579  1.400998
2  1.472691 -0.984039  1.040572  1.184362 -0.424458  1.202811  2.340509
3  0.669343  0.222716  0.408913 -0.317016  0.363334  0.463238 -0.032154
4  1.372273 -0.179536  0.672104  0.731360  0.407100  0.349457  2.244965